const charts = {
    consonants: [
        {
            name: 'voiceless bilabial plosive',
            symbol: 'p',
            row: 2,
            column: 2,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced bilabial plosive',
            symbol: 'b',
            row: 2,
            column: 3,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless bilabial fricative',
            symbol: 'ɸ',
            row: 6,
            column: 2,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced bilabial fricative',
            symbol: 'β',
            row: 6,
            column: 3,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'bilabial nasal',
            symbol: 'm',
            row: 3,
            column: 3,
            consonantal: 1,
            sonorant: 1,
            continuant: -1,
            delayedRelease: 0,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: 1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'bilabial trill',
            symbol: 'ʙ',
            row: 4,
            column: 3,
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: 1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless labiodental fricative',
            symbol: 'f',
            row: 6,
            column: 4,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: 1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: 1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced labiodental fricative',
            symbol: 'v',
            row: 6,
            column: 5,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: 1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: 1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'labiodental nasal',
            symbol: 'ɱ',
            row: 3,
            column: 5,
            consonantal: 1,
            sonorant: 1,
            continuant: -1,
            delayedRelease: 0,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: 1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: 1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'labiodental approximant',
            symbol: 'ʋ',
            row: 8,
            column: 5,
            consonantal: -1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: 1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless dental plosive',
            symbol: 't̪',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced dental plosive',
            symbol: 'd̪',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless interdental fricative',
            symbol: 'θ',
            row: 6,
            column: 6,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless interdental fricative',
            symbol: 'θ',
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced interdental fricative',
            symbol: 'ð',
            row: 6,
            column: 7,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless alveolar plosive',
            symbol: 't',
            row: 2,
            column: 8,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced alveolar plosive',
            symbol: 'd',
            row: 2,
            column: 9,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless alveolar fricative',
            symbol: 's',
            row: 6,
            column: 8,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: 1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced alveolar fricative',
            symbol: 'z',
            row: 6,
            column: 9,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: 1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'alveolar nasal',
            symbol: 'n',
            row: 3,
            column: 9,
            consonantal: 1,
            sonorant: 1,
            continuant: -1,
            delayedRelease: 0,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: 1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'alveolar lateral approximant',
            symbol: 'l',
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: 1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless lateral fricative',
            symbol: 'ɬ',
            row: 7,
            column: 8,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: 1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced lateral fricative',
            symbol: 'ɮ',
            row: 7,
            column: 9,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: 1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'alveolar flap',
            symbol: 'ɾ',
            row: 5,
            column: 9,
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: 1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'alveolar lateral flap',
            symbol: 'ɺ',
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: 1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: 1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'alveolar trill',
            symbol: 'r',
            row: 4,
            column: 9,
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: 1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless alveo-palatal fricative',
            symbol: 'ʃ',
            row: 6,
            column: 10,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: 1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced alveo-palatal fricative',
            symbol: 'ʒ',
            row: 6,
            column: 11,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: 1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'alveolar approximant',
            symbol: 'ɹ',
            row: 8,
            column: 9,
            consonantal: -1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless retroflex plosive',
            symbol: 'ʈ',
            row: 2,
            column: 12,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced retroflex plosive',
            symbol: 'ɖ',
            row: 2,
            column: 13,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless retroflex fricative',
            symbol: 'ʂ',
            row: 6,
            column: 12,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: -1,
            strident: 1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced retroflex fricative',
            symbol: 'ʐ',
            row: 6,
            column: 13,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: -1,
            strident: 1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'retroflex nasal',
            symbol: 'ɳ',
            row: 3,
            column: 13,
            consonantal: 1,
            sonorant: 1,
            continuant: -1,
            delayedRelease: 0,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: 1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'retroflex lateral approximant',
            symbol: 'ɭ',
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: -1,
            strident: -1,
            lateral: 1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'retroflex tap',
            symbol: 'ɽ',
            row: 5,
            column: 13,
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: 1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'retroflex approximant',
            symbol: 'ɻ',
            row: 8,
            column: 13,
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'strange fronted velar 1',
            symbol: '??',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'strange fronted velar 2',
            symbol: '??',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'strange fronted velar 3',
            symbol: '??',
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'palatal approximant',
            symbol: 'j',
            row: 8,
            column: 15,
            consonantal: -1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 1,
        },
        {
            name: 'voiceless velar plosive',
            symbol: 'k',
            row: 2,
            column: 16,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced velar plosive',
            symbol: 'g',
            row: 2,
            column: 17,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'velar nasal',
            symbol: 'ŋ',
            row: 3,
            column: 17,
            consonantal: 1,
            sonorant: 1,
            continuant: -1,
            delayedRelease: 0,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: 1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'velar nasal',
            symbol: 'ŋ',
            consonantal: 1,
            sonorant: 1,
            continuant: -1,
            delayedRelease: 0,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: 1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless velar fricative',
            symbol: 'x',
            row: 6,
            column: 16,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced velar fricative',
            symbol: 'ɣ',
            row: 6,
            column: 17,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'velar lateral approximant',
            symbol: 'ʟ',
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: 1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'strange backed velar 1',
            symbol: '??',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'strange backed velar 2',
            symbol: '??',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'strange backed velar 3',
            symbol: '??',
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'strange backed velar 4',
            symbol: '??',
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'voiceless uvular plosive',
            symbol: 'q',
            row: 2,
            column: 18,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: -1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'voiced uvular plosive',
            symbol: 'ɢ',
            row: 2,
            column: 19,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: -1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'voiceless uvular fricative',
            symbol: 'χ',
            row: 6,
            column: 18,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: -1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'voiced uvular fricative',
            symbol: 'ʁ',
            row: 6,
            column: 19,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: -1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'uvular nasal',
            symbol: 'ɴ',
            row: 3,
            column: 19,
            consonantal: 1,
            sonorant: 1,
            continuant: -1,
            delayedRelease: 0,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: 1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: -1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'uvular trill',
            symbol: 'ʀ',
            row: 4,
            column: 19,
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: 1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: -1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'voiceless pharyngeal fricative',
            symbol: 'ħ',
            row: 6,
            column: 20,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: -1,
            low: 1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'voiced pharyngeal fricative',
            symbol: 'ʕ',
            row: 6,
            column: 21,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: -1,
            low: 1,
            front: -1,
            back: 1,
            tense: 0,
        },
        {
            name: 'glottal stop',
            symbol: 'ʔ',
            row: 2,
            column: 22,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: 1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 0,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless glottal fricative',
            symbol: 'h',
            row: 6,
            column: 22,
            consonantal: -1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: 1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 0,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced glottal fricative',
            symbol: 'ɦ',
            row: 6,
            column: 23,
            consonantal: -1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: 1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 0,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced labial-velar approximant',
            symbol: 'w',
            consonantal: -1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: 1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: -1,
            back: 1,
            tense: 1,
        },
        {
            name: 'voiceless labial-velar fricative',
            symbol: 'ʍ',
            consonantal: -1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: 1,
            constrictedGlottis: -1,
            labial: 1,
            round: 1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: -1,
            back: 1,
            tense: 1,
        },
        {
            name: 'voiced labial-palatal approximant',
            symbol: 'ɥ',
            consonantal: -1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: 1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 1,
        },
        {
            name: 'voiceless alveolopalatal fricative',
            symbol: 'ɕ',
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: 1,
            strident: 1,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'voiced alveolopalatal fricative',
            symbol: 'ʑ',
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: 1,
            strident: 1,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'voiceless palatal plosive',
            symbol: 'c',
            row: 2,
            column: 14,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'voiced palatal plosive',
            symbol: 'ɟ',
            row: 2,
            column: 15,
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'voiceless palatal fricative',
            symbol: 'ç',
            row: 6,
            column: 14,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'voiced palatal fricative',
            symbol: 'ʝ',
            row: 6,
            column: 15,
            consonantal: 1,
            sonorant: -1,
            continuant: 1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'palatal nasal',
            symbol: 'ɲ',
            row: 3,
            column: 15,
            consonantal: 1,
            sonorant: 1,
            continuant: -1,
            delayedRelease: 0,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: 1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'palatal lateral approximant',
            symbol: 'ʎ',
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: -1,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'labiodental flap',
            symbol: 'ⱱ',
            row: 5,
            column: 5,
            consonantal: 1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: 1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: 1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'velar approximant',
            symbol: 'ɰ',
            row: 8,
            column: 17,
            consonantal: -1,
            sonorant: 1,
            continuant: 1,
            delayedRelease: 0,
            approximant: 1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: -1,
            back: 1,
            tense: 0,
        },
    ],
    vowels: [],
    otherConsonants: [],
    otherSymbols: [],
    affricates: [
        {
            name: 'voiceless labiodental affricate',
            symbol: 'p͡f',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: 1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: 1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless alveolar affricate',
            symbol: 't͡s',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: 1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced alveolar affricate',
            symbol: 'd͡z',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: 1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless alveolar lateral affricate',
            symbol: 't͡ɬ',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: -1,
            strident: -1,
            lateral: 1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless alveo-palatal affricate',
            symbol: 't͡ʃ',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: 1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced alveo-palatal affricate',
            symbol: 'd͡ʒ',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: -1,
            distributed: 1,
            strident: 1,
            lateral: -1,
            dorsal: -1,
            high: 0,
            low: 0,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless velar affricate',
            symbol: 'k͡x',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless labial-velar affricate',
            symbol: 'k͡p',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiced labial-velar affricate',
            symbol: 'g͡b',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: -1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: 1,
            round: -1,
            labiodental: -1,
            coronal: -1,
            anterior: 0,
            distributed: 0,
            strident: 0,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 0,
            back: 0,
            tense: 0,
        },
        {
            name: 'voiceless alveolopalatal affricate',
            symbol: 't͡ɕ',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: -1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: 1,
            strident: 1,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
        {
            name: 'voiced alveolopalatal affricate',
            symbol: 'd͡ʑ',
            consonantal: 1,
            sonorant: -1,
            continuant: -1,
            delayedRelease: 1,
            approximant: -1,
            tap: -1,
            trill: -1,
            nasal: -1,
            voice: 1,
            spreadGlottis: -1,
            constrictedGlottis: -1,
            labial: -1,
            round: -1,
            labiodental: -1,
            coronal: 1,
            anterior: 1,
            distributed: 1,
            strident: 1,
            lateral: -1,
            dorsal: 1,
            high: 1,
            low: -1,
            front: 1,
            back: -1,
            tense: 0,
        },
    ],
};

export default charts;
